### PR TITLE
Template create react app with typescript and react relay library

### PR DESCRIPTION
**Pull request by okel17**
This PR just includes the template react app. 

In here, we use typescript and add the react-relay repo.

### CODE REVIEW

**Comment by dsimon96** [comment]
i.e. both shipping the client code to someone's web browser and having it load and render something from the graphql endpoint

**Comment by dsimon96** [comment]
If you're feeling especially ambitious, server-side rendering

**Comment by okel17** [comment]
> Nice.
> 
> I thought of something important that you could work on: actually serving this web app from the server



> If you're feeling especially ambitious, server-side rendering

Probably not going to do this lol. The perf benefit for what we're doing is probably pretty minimal - we just do one operation of 'shortest transaction path' lol

**Comment by dsimon96** [comment]
I checked this out to confirm my environment is set up correctly for full-stack development. For the most part things went smoothly. Three questions:

1. Do you have an opinion on using npm vs. yarn? Seems like the feature set is mostly identical. I may be biased but I like Yarn a bit more - it seems a bit faster and doesn't clutter up the working directory with a node_modules folder.
2. What does react-app-rewired do for us?
3. react-app-rewired requires a simple config-overrides.js to start a development server. Should we be checking that in?

**Comment by okel17** [comment]
1. Don't care about npm vs yarn, happy to move everything to yarn. I was playing with both for installing the packages locally

2. I wanted the react app to be up and running ASAP, so I used create-react-app to kick things off. But it's easier to rewire the build commands so we can mess around with default configs. (If we really need to, we can scrap this and do it from scratch, but I'm being lazy). [Source](https://codedaily.io/tutorials/176/customize-create-react-app-without-ejecting). Anyway the config we want is [babel-plugin-relay ](https://relay.dev/docs/en/installation-and-setup)

3. Oops :P

**Pull request merged**
